steps:
  - label: ":console:"
    command: "ruby -e 'puts 42'"
    parallelism: 500
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    plugins:
      - docker#v3.7.0:
          image: "ruby:2.7-buster"
