steps:
  - input: "Input"
    key: "input"
    fields:
      - text: "Parallel agents"
        key: parallel-count
        default: 500
  - label: ":rocket: Launch containers"
    command: .buildkite/launch.sh
    depends_on: "input"
